# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bank.proto',
  package='bank',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nbank.proto\x12\x04\x62\x61nk\"C\n\x13transaction_request\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\"$\n\x11transaction_reply\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x05\x32R\n\x0btransaction\x12\x43\n\x0bMsgDelivery\x12\x19.bank.transaction_request\x1a\x17.bank.transaction_reply\"\x00\x62\x06proto3'
)




_TRANSACTION_REQUEST = _descriptor.Descriptor(
  name='transaction_request',
  full_name='bank.transaction_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='bank.transaction_request.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='bank.transaction_request.action', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='bank.transaction_request.amount', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=87,
)


_TRANSACTION_REPLY = _descriptor.Descriptor(
  name='transaction_reply',
  full_name='bank.transaction_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='balance', full_name='bank.transaction_reply.balance', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['transaction_request'] = _TRANSACTION_REQUEST
DESCRIPTOR.message_types_by_name['transaction_reply'] = _TRANSACTION_REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

transaction_request = _reflection.GeneratedProtocolMessageType('transaction_request', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION_REQUEST,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.transaction_request)
  })
_sym_db.RegisterMessage(transaction_request)

transaction_reply = _reflection.GeneratedProtocolMessageType('transaction_reply', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION_REPLY,
  '__module__' : 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.transaction_reply)
  })
_sym_db.RegisterMessage(transaction_reply)



_TRANSACTION = _descriptor.ServiceDescriptor(
  name='transaction',
  full_name='bank.transaction',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=127,
  serialized_end=209,
  methods=[
  _descriptor.MethodDescriptor(
    name='MsgDelivery',
    full_name='bank.transaction.MsgDelivery',
    index=0,
    containing_service=None,
    input_type=_TRANSACTION_REQUEST,
    output_type=_TRANSACTION_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSACTION)

DESCRIPTOR.services_by_name['transaction'] = _TRANSACTION

# @@protoc_insertion_point(module_scope)
